on: [push, pull_request]
name: Main
jobs:
  php-syntax:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: StephaneBour/actions-php-lint@7.4
      - uses: StephaneBour/actions-php-lint@7.3