# https://github.com/umutphp/php-docker-images-for-ci
on: [push, pull_request]
name: Main
jobs:
  php-check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - uses: svennd/actions-php-lint@8.0
      - uses: svennd/actions-php-lint@8.1
      - uses: svennd/php-magic-number-check-action@v1
