# https://github.com/umutphp/php-docker-images-for-ci
on:
  push:
    branches:
      - development
name: Main
jobs:
  php-check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - uses: svennd/actions-php-lint@8.1
      # - uses: StephaneBour/actions-php-lint@8.2
      # - uses: StephaneBour/actions-php-lint@8.3
      # - uses: StephaneBour/actions-php-lint@8.4
      - uses: svennd/php-magic-number-check-action@v1
