# https://github.com/umutphp/php-docker-images-for-ci
on: [push, pull_request]
name: Main
jobs:
  php-check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: svennd/actions-php-lint@7.3
      - uses: svennd/actions-php-lint@7.4
      - uses: svennd/actions-php-lint@8.0
      - name: phplint
        uses: overtrue/phplint@master
        with:
          path: .
          options: --exclude=system
      - name: php-var-dump-check
        uses: umutphp/php-var-dump-check-action@v1
        with:
          extensions: 'php'
      - uses: umutphp/php-magic-number-check-action@v1
      - uses: svennd/actions-php-cs-fixer@master
  
  phpmetrics-action:
    runs-on: ubuntu-latest
    name: PhpMetrics Action
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: PhpMetrics Scan
        uses: umutphp/phpmetrics-action@v1
      - name: Upload HTML Report
        uses: actions/upload-artifact@v1
        with:
          name: HTML Report
          path: phpmetrics.html